name: sqflite_plus
repository: https://github.com/HanQiGod/sqflite_plus/tree/main/sqflite_plus
description: Flutter 升级 3.35.7 之后，对 sqflite 插件的升级（After Flutter upgrade 3.35.7, the upgrade of sqflite plugins.）。
version: 2.5.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:

topics:
  - sql
  - database

funding:
  - https://github.com/sponsors/alextekartik

environment:
  sdk: ^3.7.0
  # Flutter versions prior to 3.7 did not support the
  # sharedDarwinSource option.
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: sqflite_plus_android
      ios:
        default_package: sqflite_plus_darwin
      macos:
        default_package: sqflite_plus_darwin

dependencies:
  flutter:
    sdk: flutter
  sqflite_plus_android: ">=2.5.0 <4.0.0"
  sqflite_plus_darwin: ">=2.5.0 <4.0.0"
  sqflite_plus_platform_interface: ">=2.5.0 <4.0.0"
  sqflite_plus_common: ">=2.6.0 <4.0.0"
  path: ">=1.8.0 <3.0.0"

dev_dependencies:
  flutter_lints: ">=5.0.0"
  process_run: ">=0.12.0"
  http: ">=0.13.0"
  flutter_test:
    sdk: flutter
  test_api: ">=0.2.19"
  pub_semver: ">=2.0.0"
